# Generated by Django 5.0 on 2023-12-07 16:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('userName', models.CharField(default=None, max_length=100)),
                ('dateOfJourney', models.DateField()),
                ('phoneNumber', models.CharField(max_length=20)),
                ('pickUpAddress', models.TextField()),
                ('dropAddress', models.TextField()),
                ('complaintRegarding', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
