# Generated by Django 5.0 on 2023-12-08 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintform',
            name='opened',
            field=models.BooleanField(default=False),
        ),
    ]
