# Generated by Django 5.0 on 2023-12-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_complaintform_opened'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintform',
            name='ComplintId',
            field=models.CharField(default='CM00000001', max_length=10, null=True),
        ),
    ]
