# Generated by Django 5.0 on 2023-12-23 14:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_complaintform_complintid'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintform',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaintform',
            name='ComplintId',
            field=models.CharField(default='CM31564027', max_length=10, null=True),
        ),
    ]
