# Generated by Django 5.0 on 2023-12-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_driverfiles_accept_flag_driverfiles_all_files_flag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverfiles',
            name='profile_photo',
            field=models.ImageField(default=None, upload_to='profile/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaintform',
            name='ComplintId',
            field=models.CharField(default='CM34075162', max_length=10, null=True),
        ),
    ]
