# Generated by Django 5.0 on 2023-12-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_driverfiles_profile_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintform',
            name='ComplintId',
            field=models.CharField(default='CM35270416', max_length=10, null=True),
        ),
    ]
