# Generated by Django 5.0 on 2023-12-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_complaintform_complintid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintform',
            name='ComplintId',
            field=models.CharField(default='CM65471302', max_length=10, null=True),
        ),
    ]
