# Generated by Django 5.0 on 2023-12-26 12:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_complaintform_complintid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintform',
            name='ComplintId',
            field=models.CharField(default='00001', max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('messages', models.CharField(max_length=1000, null=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('com_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.complaintform')),
                ('who_sent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
