# Generated by Django 5.0 on 2023-12-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_complaintform_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintform',
            name='ongoing',
            field=models.BooleanField(default=False),
        ),
    ]
