# Generated by Django 5.0 on 2023-12-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_complaintform_ongoing'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintform',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
