# Generated by Django 5.0 on 2023-12-13 14:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='airportCity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fromCity', models.CharField(max_length=200)),
                ('to', models.CharField(max_length=50)),
                ('dayRate', models.DecimalField(decimal_places=5, max_digits=100)),
                ('nightRate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('timeStamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='airportRates',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('airportName', models.CharField(max_length=200)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
