# Generated by Django 5.0 on 2023-12-13 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airportcity',
            name='fromCity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.airportrates'),
        ),
    ]
