# Generated by Django 5.0 on 2023-12-14 14:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_airportcity_fromcity'),
    ]

    operations = [
        migrations.CreateModel(
            name='businessForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('companyName', models.CharField(max_length=200)),
                ('natureOfBusiness', models.CharField(max_length=500)),
                ('websiteAddress', models.URLField()),
                ('yearCompanyEst', models.CharField(max_length=4)),
                ('contactName', models.CharField(max_length=200)),
                ('jobTitle', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=100)),
                ('telePhoneNumber', models.CharField(max_length=15)),
                ('emailAddress', models.EmailField(max_length=254)),
                ('M_CreditAmount', models.CharField(max_length=200)),
                ('M_Spend', models.CharField(max_length=50)),
                ('AuthorisedBy', models.CharField(max_length=50)),
                ('temsAndConditions', models.BooleanField(default=False)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='airportcity',
            name='timeStamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
