# Generated by Django 5.0 on 2023-12-15 16:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_rename_authorisedby_businessform_authorised_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessform',
            name='contactName',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='airportcity',
            name='dayRate',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
