# Generated by Django 5.0 on 2023-12-25 06:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_businessform_contactname_alter_airportcity_dayrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Plate_Number', models.CharField(max_length=10, null=True)),
                ('Make_or_Model', models.CharField(max_length=20, null=True)),
                ('PH_or_HC', models.CharField(max_length=2, null=True)),
                ('Number_Plate', models.CharField(max_length=20, null=True)),
                ('Color', models.CharField(max_length=20, null=True)),
                ('Plate_Expiry_Date', models.DateField(null=True)),
                ('MOT_Expiry_Date', models.DateField(null=True)),
            ],
        ),
    ]
