# Generated by Django 5.0 on 2023-12-27 14:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_fleet'),
        ('users', '0016_complaintform_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyCus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reply_mes', models.TextField(null=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('com_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.complaintform')),
                ('which_mes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.reply')),
            ],
        ),
    ]
