# Generated by Django 5.0.1 on 2024-01-09 13:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_airports_city_delete_airportcity_delete_airportrates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.airports')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.city')),
                ('who_created', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
