# Generated by Django 5.0.1 on 2024-01-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_rates_airport_name_rates_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rates',
            name='airport_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
