# Generated by Django 5.0.1 on 2024-01-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_rates_airport_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rates',
            name='city_name',
            field=models.CharField(max_length=30),
        ),
    ]
