# Generated by Django 4.2 on 2024-04-27 12:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_rates_city_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.CharField(max_length=100)),
                ('end_date', models.CharField(max_length=100)),
                ('pick_time', models.CharField(max_length=10)),
                ('drop_time', models.CharField(max_length=10)),
                ('contact_number', models.CharField(max_length=15)),
                ('pick_up_location', models.CharField(max_length=150)),
                ('drop_location', models.CharField(max_length=150)),
            ],
        ),
    ]
