# Generated by Django 4.2 on 2024-05-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_schoolcontract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolcontract',
            name='drop_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='schoolcontract',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='schoolcontract',
            name='pick_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='schoolcontract',
            name='start_date',
            field=models.DateField(),
        ),
    ]
