# Generated by Django 4.2 on 2024-05-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_alter_schoolcontract_drop_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolcontract',
            name='price',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
