# Generated by Django 4.2 on 2024-05-17 05:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_schoolcontract_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackSchoolContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.schoolcontract')),
            ],
        ),
    ]
