# Generated by Django 4.2 on 2024-05-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_trackschoolcontract'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackschoolcontract',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
