# Generated by Django 4.2 on 2024-05-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_trackschoolcontract_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolcontract',
            name='contract_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
