# Generated by Django 4.2 on 2024-05-17 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_schoolcontract_contract_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolcontract',
            old_name='contract_name',
            new_name='contract_school_name',
        ),
    ]
