# Generated by Django 4.2 on 2024-06-03 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_rename_contract_name_schoolcontract_contract_school_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolcontract',
            old_name='contact_number',
            new_name='contract_number',
        ),
        migrations.RemoveField(
            model_name='schoolcontract',
            name='drop_location',
        ),
        migrations.RemoveField(
            model_name='schoolcontract',
            name='drop_time',
        ),
        migrations.RemoveField(
            model_name='schoolcontract',
            name='pick_time',
        ),
        migrations.RemoveField(
            model_name='schoolcontract',
            name='pick_up_location',
        ),
        migrations.RemoveField(
            model_name='schoolcontract',
            name='price',
        ),
    ]
