# Generated by Django 4.2 on 2024-06-05 09:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_rename_contact_number_schoolcontract_contract_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('pickup_up_location', models.CharField(max_length=100)),
                ('drop_location', models.CharField(max_length=100)),
                ('vias', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.schoolcontract')),
            ],
        ),
    ]
