# Generated by Django 4.2 on 2024-06-05 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='pickup_up_location',
            new_name='pickup_location',
        ),
    ]
