# Generated by Django 5.0 on 2023-12-24 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extenduser',
            old_name='location',
            new_name='phone_code',
        ),
    ]
