# Generated by Django 4.2.1 on 2024-01-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_location_extenduser_phone_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminKey',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
