# Generated by Django 4.2.1 on 2024-01-21 06:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_adminkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminkey',
            name='key',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
