# Generated by Django 4.2.1 on 2024-01-21 06:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_adminkey_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminkey',
            name='key',
            field=models.CharField(default=uuid.uuid4, max_length=100),
        ),
    ]
