# Generated by Django 4.2.1 on 2024-01-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_adminkey_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminkey',
            name='key',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
