# Generated by Django 4.2.1 on 2024-01-21 06:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_adminkey_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminkey',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
